//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch12
{
    [TestFixture]
    public class _12_1Fixture : Test262Fixture
    {
        public _12_1Fixture()
            : base("ch12\\12.1")
        {
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: try-catch")]
        public void _12_1_1()
        {
            RunFile("12.1-1.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: try-catch-finally")]
        public void _12_1_2()
        {
            RunFile("12.1-2.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: try-finally")]
        public void _12_1_3()
        {
            RunFile("12.1-3.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: if-else")]
        public void _12_1_4()
        {
            RunFile("12.1-4.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: if-else-if")]
        public void _12_1_5()
        {
            RunFile("12.1-5.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: if-else-if-else")]
        public void _12_1_6()
        {
            RunFile("12.1-6.js");
        }

        [Test(Description = "12.1 - block '{ StatementListopt };' is not allowed: do-while")]
        public void _12_1_7()
        {
            RunFile("12.1-7.js");
        }

        [Test(Description = "Throwing exception within a Block")]
        public void S12_1_A2()
        {
            RunFile("S12.1_A2.js");
        }

        [Test(Description = "Checking if execution of \"y={__func}()\" fails")]
        [ExpectedException]
        public void S12_1_A4_T1()
        {
            RunFile("S12.1_A4_T1.js");
        }

        [Test(Description = "Checking if execution of \"y={x}\" fails")]
        [ExpectedException]
        public void S12_1_A4_T2()
        {
            RunFile("S12.1_A4_T2.js");
        }

        [Test(Description = "Throwing exceptions within embedded/sequence Blocks")]
        public void S12_1_A5()
        {
            RunFile("S12.1_A5.js");
        }
    }
}
