//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Jint.Test262.Ch12._12_14
{
    [TestFixture]
    public class _12_14_1Fixture : Test262Fixture
    {
        public _12_14_1Fixture()
            : base("ch12\\12.14\\12.14.1")
        {
        }

        [Test(Description = "Strict Mode - SyntaxError is thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is eval")]
        public void _12_14_1_1_s()
        {
            RunFile("12.14.1-1-s.js");
        }

        [Test(Description = "Strict Mode - SyntaxError is thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is eval")]
        [ExpectedException]
        public void _12_14_1_1gs()
        {
            RunFile("12.14.1-1gs.js");
        }

        [Test(Description = "Strict Mode - SyntaxError is thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is arguments")]
        public void _12_14_1_2_s()
        {
            RunFile("12.14.1-2-s.js");
        }

        [Test(Description = "Strict Mode - SyntaxError isn't thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is EVAL but throws SyntaxError if it is eval")]
        public void _12_14_1_3_s()
        {
            RunFile("12.14.1-3-s.js");
        }

        [Test(Description = "Strict Mode - SyntaxError isn't thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is EVAL")]
        public void _12_14_1_4_s()
        {
            RunFile("12.14.1-4-s.js");
        }

        [Test(Description = "Strict Mode - SyntaxError isn't thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is Arguments")]
        public void _12_14_1_5_s()
        {
            RunFile("12.14.1-5-s.js");
        }

        [Test(Description = "Strict Mode - SyntaxError isn't thrown if a TryStatement with a Catch occurs within strict code and the Identifier of the Catch production is ARGUMENTS")]
        public void _12_14_1_6_s()
        {
            RunFile("12.14.1-6-s.js");
        }
    }
}
